### ISSUE TITLE
抱歉 我想问一个问题

### ISSUE THREAD

**Issue by xfqwdsj** [CopyTranslator/copytranslator.github.io#1]
在这里打扰了 抱歉 我也很想把pages做成这样 请问怎么做呢？

**Comment by wxchencn** [comment]
看这个主题应该用的是[VuePress](https://vuepress.vuejs.org/zh/)

**Comment by xfqwdsj** [comment]
> 看这个主题应该用的是[VuePress](https://vuepress.vuejs.org/zh/)

谢谢你
